(() => {
  const cfg = window.APP_CONFIG || {};
  const status = document.getElementById("status"); const form = document.getElementById("profileForm");
  function setStatus(message,type=""){status.textContent=message;status.className="status"+(type?" "+type:"");}
  if(!cfg.supabaseUrl||cfg.supabaseUrl.includes("YOUR-PROJECT")||!cfg.supabaseAnonKey||cfg.supabaseAnonKey.includes("YOUR_PUBLIC")){setStatus("Site setup isn’t finished yet. Supabase details are missing from config.js.","error");return;}
  const token=new URLSearchParams(window.location.search).get("token"); if(!token){setStatus("This edit link is missing its private token.","error");return;}
  const client=supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
  const fields=["name","birthday","address","phone","email","favourite_flower","favourite_treat","favourite_drink","hobbies","likes","dislikes"];
  function fill(data){fields.forEach(k=>{const el=document.getElementById(k);if(el)el.value=data[k]??"";});document.getElementById("pageTitle").textContent=`${data.name} — your details`;form.hidden=false;}
  function renderFamily(data){const section=document.getElementById('familySection');if(!section||!data)return;const household=data.household;const rels=data.relationships||[];const anns=data.anniversaries||[];if(!household&&rels.length===0&&anns.length===0)return;if(household){document.getElementById('householdName').textContent=household.name;const names=(household.members||[]).map(m=>m.name);document.getElementById('householdMembers').textContent=names.length?`Household: ${names.join(' · ')}`:'';}else{document.getElementById('householdName').textContent='Your family connections';}
    if(rels.length){const wrap=document.getElementById('relationshipsWrap');wrap.hidden=false;const chips=document.getElementById('relationshipChips');chips.innerHTML='';rels.forEach(r=>{const span=document.createElement('span');span.textContent=`${r.name} — ${r.relationship}`;chips.appendChild(span);});}
    if(anns.length){const wrap=document.getElementById('anniversariesWrap');wrap.hidden=false;const list=document.getElementById('anniversaryList');list.innerHTML='';anns.forEach(a=>{const d=new Date(`${a.anniversary_date}T12:00:00`);const div=document.createElement('div');div.className='anniversary-item';div.textContent=`♡ ${a.with_name} · ${d.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}`;list.appendChild(div);});}
    section.hidden=false;
  }
  async function load(showLoaded=true){if(showLoaded)setStatus("Loading your profile…");const [{data,error},{data:familyData,error:familyError}]=await Promise.all([client.rpc("get_person_by_token",{p_token:token}),client.rpc("get_person_family_by_token",{p_token:token})]);if(error||!data||data.length===0){setStatus("This link is invalid or has expired.","error");return false;}fill(data[0]);if(!familyError)renderFamily(familyData);if(showLoaded)setStatus("Loaded. Make any changes below.");return true;}
  form.addEventListener("submit",async e=>{e.preventDefault();const button=form.querySelector('button[type="submit"]');if(button){button.disabled=true;button.textContent='Saving…';}setStatus("Saving your changes…");const payload={p_token:token,p_address:document.getElementById("address").value.trim(),p_phone:document.getElementById("phone").value.trim(),p_email:document.getElementById("email").value.trim(),p_favourite_flower:document.getElementById("favourite_flower").value.trim(),p_favourite_treat:document.getElementById("favourite_treat").value.trim(),p_favourite_drink:document.getElementById("favourite_drink").value.trim(),p_hobbies:document.getElementById("hobbies").value.trim(),p_likes:document.getElementById("likes").value.trim(),p_dislikes:document.getElementById("dislikes").value.trim()};const {data,error}=await client.rpc("update_person_by_token",payload);if(error||data!==true){console.error(error);setStatus("I couldn’t save that. Please try again.","error");if(button){button.disabled=false;button.textContent='Save changes ♡';}return;}setStatus("✓ Details updated successfully! Refreshing your profile…","success");await new Promise(r=>setTimeout(r,900));const refreshed=await load(false);if(refreshed)setStatus("✓ Your details are up to date and shown below.","success");if(button){button.disabled=false;button.textContent='Save changes ♡';}window.scrollTo({top:0,behavior:'smooth'});});
  load();
})();
